# Quick Story Workflow - Streamlined Feature Planning
name: quick-story
description: "Compact, fast planning for medium-sized features. ~50% faster than full implementation-story while maintaining quality."
author: "Claude Workflows"

# Project variables (will be resolved from project context)
project_name: runtime-captured
output_folder: "{project-root}/docs"
dev_story_location: "{project-root}/docs/stories"
user_name: runtime-captured
communication_language: English
document_output_language: English
user_skill_level: intermediate
date: system-generated

# Runtime variables (captured during workflow execution)
story_slug: runtime-captured
branch_name: runtime-captured
feature_description: runtime-captured

# Workflow components (local paths relative to workflow location)
installed_path: "{workflow-dir}"
instructions: "{installed_path}/instructions.md"
template: "{installed_path}/story-template.md"
checklist: "{installed_path}/checklist.md"

# Output configuration
default_output_file: "{dev_story_location}/{{story_slug}}.md"

# Standalone mode (no dependency on previous workflows)
standalone: true

# Differences from implementation-story:
# - 4 steps instead of 8 (combined)
# - 1 exploration agent instead of 3
# - Fewer user checkpoints
# - Compact template (~15 fields vs ~30)
# - Optimized for #yolo mode
